# Nom du workflow
name: Python Application CI

# Déclencheurs
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Tâches
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Étape 2 : Configurer Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Étape 3 : Installer les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # ÉTAPE 4 : NOUVELLE ÉTAPE IMPORTANTE !
    # Créer la base de données de test avant de lancer les tests.
    - name: Prepare test database
      run: |
        python tests/setup_test_db.py

    # Étape 5 : Lancer les tests
    - name: Run tests with pytest
      run: |
        pytest